theory Chapter_3
  imports Main

begin

text \<open>Section 3.2 Sets\<close>

text \<open>
How @{typ "'a set"} is defined (not a datatype)
\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>
Unlike @{typ nat} or @{typ "'a list"}, the type @{typ "'a set"} is
\emph{not} introduced by @{command datatype}. In @{file \<open>~~/src/HOL/Set.thy\<close>}
it is an abstract type:

  typedecl 'a set

  axiomatization
    Collect :: "('a \<Rightarrow> bool) \<Rightarrow> 'a set"     \<comment> \<open>comprehension {x. P x}\<close>
    and member :: "'a \<Rightarrow> 'a set \<Rightarrow> bool"    \<comment> \<open>membership (\<in>)\<close>
  where
    "member a (Collect P) = P a"
  | "Collect (\<lambda>x. member x A) = A"

So a set is essentially a predicate (characteristic function). Derived
notions include @{term "{}"} (empty), @{term UNIV} (all elements of the
type), @{term insert}, enumerations @{term "{a,b}"}, union, etc.
Because there are no free constructors, one cannot define functions on
arbitrary sets by structural recursion the way one does on lists.


The function @{const set} on lists
\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>
The constant @{const set} :: @{typ "'a list \<Rightarrow> 'a set"} is \emph{not}
user-defined under @{theory Main}; it is generated by the datatype
package when lists are declared:

  datatype (set: 'a) list =
      Nil  ("[]")
    | Cons (hd: 'a) (tl: "'a list")  (infixr "#" 65)

The annotation @{text "(set: 'a)"} builds the element-set function.
The equations (see @{thm list.set}) are:

  set [] = {}
  set (x # xs) = insert x (set xs)

which is the same as @{term "{x} \<union> set xs"} because
@{prop "insert x A = {x} \<union> A"}.


How finiteness is defined
\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>
@{const finite} cannot be a @{command fun} either: sets are not a
datatype, and infinite sets exist. Instead Isabelle defines finiteness
\emph{inductively} as the least predicate closed under empty and insert
(@{file \<open>~~/src/HOL/Finite_Set.thy\<close>}):

  inductive finite :: "'a set \<Rightarrow> bool" where
    "finite {}"
  | "finite A \<Longrightarrow> finite (insert a A)"

Infinity is just the negation:

  abbreviation infinite :: "'a set \<Rightarrow> bool"
    where "infinite S \<equiv> \<not> finite S"

So one does not introduce separate constructors for infinite sets;
@{term "infinite A"} means @{term A} lies outside that inductive
closure. Standard facts include @{prop "finite (set xs)"} (every list
has finitely many elements) and @{prop "infinite (UNIV :: nat set)"}.
\<close>

thm list.set
value "set [(1::nat), 2]"
value "set ([] :: int list)"

lemma "finite (set xs)" by simp
lemma "infinite (UNIV :: nat set)" by simp

text \<open>Section 3.3 Proof Automation\<close>

lemma "\<forall>x. \<exists>y. x = y"
  by auto

lemma "x \<in> X\<inter>Y \<Longrightarrow> x \<in> X\<union>Y"
  by auto

text \<open>
  by proof-method
  is short for
  apply proof-method
  done
\<close>

(* lemma "(\<forall>xs \<in> A. \<exists>ys. xs = ys @ ys) \<and> (us \<in> A) \<Longrightarrow> \<exists>n. length us = n + n"
   prefer the following version: *)
lemma "\<lbrakk>\<forall>xs \<in> A. \<exists>ys. xs = ys @ ys; us \<in> A\<rbrakk> \<Longrightarrow> \<exists>n. length us = n + n"
  by fastforce

lemma "\<lbrakk> \<forall>x y. T x y \<or> T y x;
         \<forall>x y. A x y \<and> A y x \<longrightarrow> x = y;
         \<forall>x y. T x y \<longrightarrow> A x y \<rbrakk>
      \<Longrightarrow> \<forall>x y. A x y \<longrightarrow> T x y"
  by blast

text \<open>section 3.3.1 Sledgehammer\<close>

lemma "\<lbrakk>xs @ ys = ys @ xs; length xs = length ys\<rbrakk> \<Longrightarrow> xs = ys"
  by(metis append_eq_conv_conj)

text "
  the lemma append_eq_conv_conj is:
  (xs @ ys = zs) = (xs = take (length xs) zs \<and> ys = drop (length xs) zs)

  from lemma and the first assumption:
  xs = take (length xs) (ys @ xs)
  ys = drop (length xs) (ys @ xs)
  ys = take (length ys) (xs @ ys)
  xs = drop (length ys) (xs @ ys)
  again with the first and the second assumption, it's obviously that
  xs = ys
"

text \<open>section 3.3.2 Arithmetic\<close>

lemma "\<lbrakk>(a::nat) \<le> x + b; 2 * x < c\<rbrakk> \<Longrightarrow> 2 * a + 1 \<le> 2 * b + c"
  by arith \<comment> \<open>can be proved directly by simpification\<close>

end
