theory Chapter_3
  imports Main

begin

text \<open>Section 3.2 Sets\<close>

text \<open>
How @{typ "'a set"} is defined (not a datatype)
\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>
Unlike @{typ nat} or @{typ "'a list"}, the type @{typ "'a set"} is
\emph{not} introduced by @{command datatype}. In @{file \<open>~~/src/HOL/Set.thy\<close>}
it is an abstract type:

  typedecl 'a set

  axiomatization
    Collect :: "('a \<Rightarrow> bool) \<Rightarrow> 'a set"     \<comment> \<open>comprehension {x. P x}\<close>
    and member :: "'a \<Rightarrow> 'a set \<Rightarrow> bool"    \<comment> \<open>membership (\<in>)\<close>
  where
    "member a (Collect P) = P a"
  | "Collect (\<lambda>x. member x A) = A"

So a set is essentially a predicate (characteristic function). Derived
notions include @{term "{}"} (empty), @{term UNIV} (all elements of the
type), @{term insert}, enumerations @{term "{a,b}"}, union, etc.
Because there are no free constructors, one cannot define functions on
arbitrary sets by structural recursion the way one does on lists.


The function @{const set} on lists
\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>
The constant @{const set} :: @{typ "'a list \<Rightarrow> 'a set"} is \emph{not}
user-defined under @{theory Main}; it is generated by the datatype
package when lists are declared:

  datatype (set: 'a) list =
      Nil  ("[]")
    | Cons (hd: 'a) (tl: "'a list")  (infixr "#" 65)

The annotation @{text "(set: 'a)"} builds the element-set function.
The equations (see @{thm list.set}) are:

  set [] = {}
  set (x # xs) = insert x (set xs)

which is the same as @{term "{x} \<union> set xs"} because
@{prop "insert x A = {x} \<union> A"}.


How finiteness is defined
\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>\<midarrow>
@{const finite} cannot be a @{command fun} either: sets are not a
datatype, and infinite sets exist. Instead Isabelle defines finiteness
\emph{inductively} as the least predicate closed under empty and insert
(@{file \<open>~~/src/HOL/Finite_Set.thy\<close>}):

  inductive finite :: "'a set \<Rightarrow> bool" where
    "finite {}"
  | "finite A \<Longrightarrow> finite (insert a A)"

Infinity is just the negation:

  abbreviation infinite :: "'a set \<Rightarrow> bool"
    where "infinite S \<equiv> \<not> finite S"

So one does not introduce separate constructors for infinite sets;
@{term "infinite A"} means @{term A} lies outside that inductive
closure. Standard facts include @{prop "finite (set xs)"} (every list
has finitely many elements) and @{prop "infinite (UNIV :: nat set)"}.
\<close>

thm list.set
value "set [(1::nat), 2]"
value "set ([] :: int list)"

lemma "finite (set xs)" by simp
lemma "infinite (UNIV :: nat set)" by simp

end
