theory Rule_Induction_Notes
  imports Chapter_4
begin

text \<open>
  Companion to section 4.4.7 of @{file \<open>Chapter_4.thy\<close>}.  Distilled from the
  discussion of
    @{prop "ev (Suc m) \<Longrightarrow> \<not> ev m"}
  and of how Isabelle manufactures a rule-induction principle.

  The claim of this note: rule induction is not an extra axiom bolted onto
  @{command inductive}.  It is the elimination principle for the
  \emph{least fixed point} of the monotone operator generated by the
  introduction rules --- the same ``least closed object'' idea that
  computation induction uses for a @{command fun}.
\<close>


section \<open>One idea, three induction schemas\<close>

text \<open>
  Something defined as ``the least object closed under these constructions''
  always comes with an induction principle: to prove a property @{text P} of
  every inhabitant, show that @{text P} itself is closed under the same
  constructions.

  Isabelle offers three surface forms of that idea.

  \<^item> \emph{Structural induction} (@{text "induction xs"} on a datatype).
    The constructions are the constructors.  @{typ nat} is the least set
    containing @{term 0} and closed under @{const Suc}, so the cases are
    @{text "P 0"} and @{text "P n \<Longrightarrow> P (Suc n)"}.

  \<^item> \emph{Computation induction} (@{text "induction rule: f.induct"}).
    The constructions are the defining equations of a @{command fun}.
    Each equation becomes a case; each recursive call becomes an IH.
    See @{const evn} below, @{const pair_count} in Chapter~4, and @{text div2}
    in Chapter~2.

  \<^item> \emph{Rule induction} (@{text "induction rule: I.induct"}).
    The constructions are the introduction rules of an
    @{command inductive} predicate.  Each rule becomes a case; each
    \emph{recursive} premise becomes an IH.

  In all three, you induct along the way the object was \emph{built}:
  constructor tree, computation tree, or derivation tree.
\<close>


section \<open>From introduction rules to the induction rule\<close>

text \<open>
  @{const ev} is the least predicate closed under

    @{thm ev0}      and      @{thm evSS}.

  ``Least'' means: if any other predicate @{text P} is closed under the same
  two rules, then @{const ev} is contained in @{text P}.  That containment
  \emph{is} @{thm [source] ev.induct}:
\<close>

thm ev.induct

text \<open>
  Isabelle obtains this theorem by a mechanical rewrite of each introduction
  rule.  Write a rule as

    @{text "\<lbrakk> side conditions;  I t\<^sub>1;  I t\<^sub>2;  \<dots> \<rbrakk> \<Longrightarrow> I t"}

  \<^item> Keep every \emph{side condition} (a premise that does not mention @{text I})
    unchanged.  It contributes no IH.
  \<^item> For every \emph{recursive premise} @{text "I t\<^sub>i"}, keep @{text "I t\<^sub>i"}
    (@{text hyps}) and add @{text "P t\<^sub>i"} (@{text IH}).
  \<^item> Replace the conclusion @{text "I t"} by @{text "P t"}.

  A rule with no recursive premise (a base rule) contributes only @{text "P t"}.

  Applied to @{const ev}:

    @{text ev0}:   @{prop "ev 0"}
      becomes  @{text "P 0"}

    @{text evSS}:  @{prop "ev m \<Longrightarrow> ev (Suc (Suc m))"}
      becomes  @{text "ev m \<Longrightarrow> P m \<Longrightarrow> P (Suc (Suc m))"}

  Glue the cases to the assumption @{text "ev x"} and you have
  @{thm [source] ev.induct}.  The two premises of the @{text evSS} case are
  therefore of different origin:

    @{text "ev m"}  --- leftover from the introduction rule (@{text evSS.hyps})
    @{text "P m"}   --- added by the rewrite (@{text evSS.IH})

  The introduction rule itself still has only one premise.  The second
  hypothesis appears only in the \emph{induction} rule, because induction
  asks whether @{text P} already holds for the smaller derivation.

  The same rewrite on the reflexive-transitive closure (Chapter~3)

    @{text "refl:  star f x x"}
    @{text "step:  f x y \<Longrightarrow> star f y z \<Longrightarrow> star f x z"}

  yields

    @{text "P x x"}
    @{text "f x y \<Longrightarrow> star f y z \<Longrightarrow> P y z \<Longrightarrow> P x z"}

  Here @{text "f x y"} is a side condition (no @{text star}, so no IH);
  @{text "star f y z"} is the only recursive premise.  A @{text "for"}
  parameter such as @{text f} is fixed and is not an argument of @{text P}.
\<close>


section \<open>Least fixed point\<close>

text \<open>
  The rewrite above is the surface form of a least-fixed-point argument.

  Collect the introduction rules into a monotone operator @{text \<Phi>} on
  predicates.  For @{const ev}:
\<close>

definition ev_\<Phi> :: "(nat \<Rightarrow> bool) \<Rightarrow> nat \<Rightarrow> bool" where
  "ev_\<Phi> Q n \<longleftrightarrow> n = 0 \<or> (\<exists>m. n = Suc (Suc m) \<and> Q m)"

text \<open>
  Reading: @{term n} is in @{term "ev_\<Phi> Q"} when it can be justified by
  one application of @{text ev0} or @{text evSS}, using @{text Q} for the
  recursive premise.  Monotonicity is immediate: larger @{text Q} gives a
  larger @{term "ev_\<Phi> Q"}.

  @{const ev} is a \emph{fixed point} of @{const ev_\<Phi>} --- applying the
  rules once more produces nothing new:
\<close>

lemma ev_is_fixed_point: "ev_\<Phi> ev n = ev n"
proof (rule iffI)
  assume "ev_\<Phi> ev n"
  hence "n = 0 \<or> (\<exists>m. n = Suc (Suc m) \<and> ev m)"
    unfolding ev_\<Phi>_def by simp
  thus "ev n"
  proof
    assume "n = 0"
    thus "ev n" by (simp add: ev0)
  next
    assume "\<exists>m. n = Suc (Suc m) \<and> ev m"
    then obtain m where "n = Suc (Suc m)" "ev m" by blast
    thus "ev n" by (simp add: evSS)
  qed
next
  assume "ev n"
  thus "ev_\<Phi> ev n"
  proof cases
    case ev0
    thus ?thesis unfolding ev_\<Phi>_def by simp
  next
    case evSS
    thus ?thesis unfolding ev_\<Phi>_def by blast
  qed
qed

text \<open>
  It is the \emph{least} fixed point: any @{text P} that is already closed
  under @{const ev_\<Phi>} (a prefixpoint @{term "ev_\<Phi> P \<le> P"}) contains
  @{const ev}.  That is Knaster--Tarski induction, and it is derivable from
  @{thm [source] ev.induct}:
\<close>

lemma ev_least:
  assumes closed: "\<And>n. ev_\<Phi> P n \<Longrightarrow> P n"
  shows "ev n \<Longrightarrow> P n"
proof (induction rule: ev.induct)
  case ev0
  show ?case
    using closed[of 0] unfolding ev_\<Phi>_def by simp
next
  case (evSS m)
  show ?case
    using closed[of "Suc (Suc m)"] evSS.IH unfolding ev_\<Phi>_def by blast
qed

text \<open>
  Two slightly different ``closed'' obligations appear in the literature
  and in Isabelle:

  \<^item> \emph{Prefixpoint} (as in @{thm [source] ev_least}):
      @{text "P 0"} and @{text "P m \<Longrightarrow> P (Suc (Suc m))"} for every @{text m}.
  \<^item> \emph{Closed under the rules} (as in @{thm [source] ev.induct}):
      @{text "P 0"} and @{text "ev m \<Longrightarrow> P m \<Longrightarrow> P (Suc (Suc m))"}.

  The second is easier to discharge: the step is required only for numbers
  that are already even.  Isabelle ships this form because rule induction
  is induction on the \emph{derivation}, so the recursive premise
  @{prop "ev m"} is sitting there as @{text hyps}.

  Either way the essence is the same: @{const ev} contains nothing but what
  the rules force, so a property that the rules preserve holds of every
  even number.
\<close>


section \<open>Computation induction is the same idea\<close>

text \<open>
  A @{command fun} is the unique solution of its equations, obtained as
  the least (well-founded) fixed point of the recursion operator.  The
  derived rule @{text f.induct} is induction along that computation.

  @{const evn} is the executable counterpart of @{const ev}:
\<close>

thm evn.induct

text \<open>
  The three cases are exactly the three equations, and the only IH sits
  on the recursive call @{term "evn m"}:

    @{text "P 0"}
    @{text "P (Suc 0)"}
    @{text "P m \<Longrightarrow> P (Suc (Suc m))"}

  Contrast with @{thm [source] ev.induct}:

    @{text "P 0"}
    @{text "ev m \<Longrightarrow> P m \<Longrightarrow> P (Suc (Suc m))"}

  \<^item> Computation induction ranges over \emph{every} @{typ nat}, because a
    @{command fun} is total.  The odd case @{term "Suc 0"} is a real
    equation and a real case.
  \<^item> Rule induction ranges only over the \emph{derivable} trees.  There is
    no @{text ev} rule for @{term "Suc 0"}, so there is no corresponding
    induction case.  Odds are excluded from the start.

  That is why @{prop "ev m \<Longrightarrow> evn m"} is a two-case rule induction
  (Chapter~4, section 4.4.4), while @{prop "evn m \<Longrightarrow> ev m"} is a
  three-case computation induction: the middle goal is @{prop "ev (Suc 0)"},
  which is vacuously discharged once the assumption @{prop "evn (Suc 0)"}
  has been simplified to @{const False}.

  The rewrite recipe is again the same, with ``recursive call'' in place of
  ``recursive premise''.  For @{const pair_count} the third equation calls
  @{term "pair_count xs"}, so @{text pair_count.induct} supplies an IH for
  @{term xs} and none for the discarded heads.

  Heuristic (Chapter~2): if the equations are not one-per-constructor, prefer
  @{text f.induct} over structural induction.  Structural induction on
  @{typ nat} does not know that @{const evn} peels \emph{two} @{const Suc}s,
  just as it does not know that @{const ev} is generated by @{text evSS}.
\<close>


section \<open>What @{text P} is --- and what it is not\<close>

text \<open>
  @{thm [source] ev.induct} always proves something of the shape
    @{text "ev n \<Longrightarrow> P n"}.
  The assumption @{text "ev n"} is the induction \emph{hook}.  It is not
  part of @{text P}.  @{text P} is only the conclusion, arranged as a
  property of the number being inducted on.

  In the easy lemma @{prop "ev m \<Longrightarrow> evn m"} one has @{text "P = evn"},
  i.e.\ @{text "P n = evn n"}.  The lemma is @{text "ev m \<Longrightarrow> P m"};
  @{text P} is the succedent, not the whole statement.

  The last lemma of section 4.4.7 is

    @{prop "ev (Suc m) \<Longrightarrow> \<not> ev m"}.

  The succedent @{prop "\<not> ev m"} is \emph{not} a property of the induction
  term @{term "Suc m"}: it talks about @{term m}.  Freezing @{term m} and
  taking @{text "P n = (\<not> ev m)"} makes @{text "P (Suc m)"} look right,
  but the IH is then about that same frozen @{term m} and does not move
  when the derivation grows.

  @{text "arbitrary: m"} therefore generalizes @{term m} \emph{before}
  induction.  The property actually used is
\<close>

definition odd_pred :: "nat \<Rightarrow> bool" where
  "odd_pred n \<longleftrightarrow> (\<forall>m. n = Suc m \<longrightarrow> \<not> ev m)"

text \<open>
  So @{term "odd_pred n"} means: if @{term n} is a successor, its
  predecessor is not even.  This is a property of @{term n} alone, and it
  specializes to the lemma:

    @{term "odd_pred (Suc m)"}  reduces to  @{prop "\<not> ev m"}.

  @{text P} is @{const odd_pred}, not the lemma as a whole, and not the
  bare succedent @{prop "\<not> ev m"}.
\<close>

lemma odd_pred_ev: "ev n \<Longrightarrow> odd_pred n"
proof (induction rule: ev.induct)
  case ev0
    \<comment> \<open>@{term "odd_pred 0"} is @{text "\<forall>m. 0 = Suc m \<longrightarrow> \<not> ev m"}, vacuous\<close>
  show ?case unfolding odd_pred_def by simp
next
  case (evSS k)
  show "odd_pred (Suc (Suc k))"
    unfolding odd_pred_def
  proof (intro allI impI)
    fix m
    assume "Suc (Suc k) = Suc m"
    hence "m = Suc k" by simp
    show "\<not> ev m"
    proof
      assume "ev m"
      hence "ev (Suc k)" using \<open>m = Suc k\<close> by simp
      thus False
      proof cases
          \<comment> \<open>@{text ev0} cannot fire: @{term "Suc k"} is not @{term 0}\<close>
        fix j
        assume "k = Suc j" "ev j"
        then have "\<not> ev j"
          using evSS.IH unfolding odd_pred_def by simp
        thus False using \<open>ev j\<close> by blast
      qed
    qed
  qed
qed

lemma ev_Suc_not_ev: "ev (Suc m) \<Longrightarrow> \<not> ev m"
  using odd_pred_ev[of "Suc m"] unfolding odd_pred_def by simp


section \<open>Reading the command in section 4.4.7\<close>

text \<open>
  Chapter~4 proves the same fact without naming @{const odd_pred}, by

    @{text "proof (induction \"Suc m\" arbitrary: m rule: ev.induct)"}

  Three instructions, one line:

  \<^item> @{text "rule: ev.induct"} --- use the least-fixed-point / derivation
    induction of @{const ev}, not structural induction on @{typ nat}.
  \<^item> @{text "\"Suc m\""} --- the hook is @{prop "ev (Suc m)"}, so the
    induction term is @{term "Suc m"}, not some other occurrence of
    @{const ev}.
  \<^item> @{text "arbitrary: m"} --- generalize @{term m}, i.e.\ take
    @{text P} to be @{const odd_pred}.

  Unfolding @{thm [source] ev.induct} at @{text "P = odd_pred"}:

  \<^item> @{text ev0} asks for @{term "odd_pred 0"}, which is vacuous.  Isabelle
    discharges it, so only one subgoal remains.
  \<^item> @{text evSS} asks for
      @{text "ev n \<Longrightarrow> odd_pred n \<Longrightarrow> odd_pred (Suc (Suc n))"}.
    The conclusion simplifies: @{term "odd_pred (Suc (Suc n))"} is
    @{prop "\<not> ev (Suc n)"}.  Reusing the original name @{text m} for
    @{text n} and @{text ma} for the bound variable of the IH yields
    exactly the leftover goal in Chapter~4:

      @{text "\<And>m. ev m \<Longrightarrow> (\<And>ma. m = Suc ma \<Longrightarrow> \<not> ev ma) \<Longrightarrow> \<not> ev (Suc m)"}

  That goal is \emph{not} the original lemma and is \emph{not} ``just
  @{text evSS}''.  It is the successor case of ``@{const ev} is below
  @{const odd_pred}''.  The first premise is @{text hyps}; the second is
  @{text IH} @{text "="} @{term "odd_pred m"}.

  The Isar text that follows only renames @{text m} to @{text n}, drops
  the unused @{text hyps}, and shows @{prop "\<not> ev (Suc n)"}.  The inner
  @{text cases} is rule inversion of @{prop "ev (Suc n)"}: the only
  possible rule is @{text evSS}, giving @{text "n = Suc k"} and
  @{prop "ev k"}, which the IH refutes.
\<close>

lemma ev_Suc_not_ev_inline: "ev (Suc m) \<Longrightarrow> \<not> ev m"
proof (induction "Suc m" arbitrary: m rule: ev.induct)
  fix n assume IH: "\<And>m. n = Suc m \<Longrightarrow> \<not> ev m"
    \<comment> \<open>this is @{term "odd_pred n"}; @{prop "ev n"} is unused\<close>
  show "\<not> ev (Suc n)"
    \<comment> \<open>this is @{term "odd_pred (Suc (Suc n))"}\<close>
  proof
    assume "ev (Suc n)"
    thus False
    proof cases
      fix k assume "n = Suc k" "ev k"
      thus False using IH by auto
    qed
  qed
qed


section \<open>Summary\<close>

text \<open>
  \<^item> An inductive predicate is the least fixed point of the operator
    assembled from its introduction rules.  Rule induction is the
    corresponding elimination principle: @{text "I \<subseteq> P"} once @{text P}
    is closed under those rules.

  \<^item> Isabelle writes that principle down by decorating every recursive
    premise @{text "I t\<^sub>i"} with an extra @{text "P t\<^sub>i"}.  Side conditions
    stay as they are.  That is why the @{text evSS} \emph{induction}
    case has two assumptions while the @{text evSS} \emph{introduction}
    rule has one.

  \<^item> Computation induction is the same least-fixed-point story for a
    @{command fun}: cases follow equations, IHs follow recursive calls,
    and the induction ranges over the whole domain rather than over a
    derivable subset.

  \<^item> @{text P} is the conclusion, rephrased as a predicate on the
    induction term.  It is never the whole lemma (the @{const ev}
    assumption is the hook, not part of @{text P}).  When the conclusion
    mentions a variable that also occurs inside the induction term, that
    variable must be generalized --- by an explicit definition such as
    @{const odd_pred}, or by @{text "arbitrary:"} --- before the
    least-fixed-point argument applies.
\<close>

end
